trigger:
  branches:
    include:
      - main
      - stable/*
  tags:
    include:
      - '*'
pool:
  name: 'VN Linux'

resources:
  repositories:
    - repository: infra-templates
      type: git
      name: Sync_template
      ref: refs/heads/main

variables:
  - group: AZDO_Credentials

lockBehavior: sequential
stages:
  - stage: Sync_ADO_To_Github
    jobs:
      - job: Sync
        steps:
          - template: github-to-ado.yaml@infra-templates
            parameters:
              GITHUB_REPO_LINK: 'https://github.com/binhnguyen-bit/Test_Sync.git'
              REPO_NAME: 'Test_Sync'